<?php

use Illuminate\Database\Seeder;
use App\Country;
class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ["en"=>"Afghanistan","ru"=>"Афганистан"],
            ["en"=>"Albania","ru"=>"Албания"],
            ["en"=>"Algeria","ru"=>"Алжир"],
            ["en"=>"American Samoa","ru"=>"Самоа (США)"],
            ["en"=>"Andorra","ru"=>"Андорра"],
            ["en"=>"Angola","ru"=>"Ангола"],
            ["en"=>"Anguilla","ru"=>"Ангуилла"],
            ["en"=>"Antarctica","ru"=>"Антарктика"],
            ["en"=>"Antigua and Barbuda","ru"=>"Антигуа и Барбуда"],
            ["en"=>"Argentina","ru"=>"Аргентина"],
            ["en"=>"Armenia","ru"=>"Армения"],
            ["en"=>"Aruba","ru"=>"Аруба"],
            ["en"=>"Australia","ru"=>"Австралия"],
            ["en"=>"Austria","ru"=>"Австрия"],
            ["en"=>"Azerbaijan","ru"=>"Азербайджан"],
            ["en"=>"Bahrain","ru"=>"Бахрейн"],
            ["en"=>"Bangladesh","ru"=>"Бангладеш"],
            ["en"=>"Barbados","ru"=>"Барбадос"],
            ["en"=>"Belarus","ru"=>"Беларусь"],
            ["en"=>"Belgium","ru"=>"Бельгия"],
            ["en"=>"Belize","ru"=>"Белиз"],
            ["en"=>"Benin","ru"=>"Бенин"],
            ["en"=>"Bermuda","ru"=>"Бермуды"],
            ["en"=>"Bhutan","ru"=>"Бутан"],
            ["en"=>"Bolivia","ru"=>"Боливия"],
            ["en"=>"Bosnia and Herzegovina","ru"=>"Босния-Герцеговина"],
            ["en"=>"Botswana","ru"=>"Ботсвана"],
            ["en"=>"Bouvet Island","ru"=>"Боуветские острова"],
            ["en"=>"Brazil","ru"=>"Бразилия"],
            ["en"=>"British Indian Ocean Territory","ru"=>"Старые Британские Индийские Территории"],
            ["en"=>"British Virgin Islands","ru"=>"	Вирджинские острова"],
            ["en"=>"Brunei","ru"=>"Бруней"],
            ["en"=>"Bulgaria","ru"=>"Болгария"],
            ["en"=>"Burkina Faso","ru"=>"Буркина-Фасо"],
            ["en"=>"Burundi","ru"=>"Бурунди"],
            ["en"=>"Côte d'Ivoire","ru"=>"Берег Слоновой Кости"],
            ["en"=>"Cambodia","ru"=>"Камбоджа"],
            ["en"=>"Cameroon","ru"=>"Камерун"],
            ["en"=>"Canada","ru"=>"Канада"],
            ["en"=>"Cape Verde","ru"=>"Кабо-Верде"],
            ["en"=>"Cayman Islands","ru"=>"Каймановы острова"],
            ["en"=>"Central African Republic","ru"=>"Центрально-Африканская Республика"],
            ["en"=>"Chad","ru"=>"Чад"],
            ["en"=>"Chile","ru"=>"Чили"],
            ["en"=>"China","ru"=>"Китай"],
            ["en"=>"Christmas Island","ru"=>"Рождественские острова"],
            ["en"=>"Cocos (Keeling) Islands","ru"=>"Кокосовые острова"],
            ["en"=>"Colombia","ru"=>"Колумбия"],
            ["en"=>"Comoros","ru"=>"Коморос"],
            ["en"=>"Congo","ru"=>"Конго"],
            ["en"=>"Cook Islands","ru"=>"Острова Кука"],
            ["en"=>"Costa Rica","ru"=>"Коста Рикa"],
            ["en"=>"Croatia","ru"=>"Хорватия"],
            ["en"=>"Cuba","ru"=>"Куба"],
            ["en"=>"Cyprus","ru"=>"Кипр"],
            ["en"=>"Czech Republic","ru"=>"Чешская Республика"],
            ["en"=>"Democratic Republic of the Congo","ru"=>"Демократическая Республика Конго"],
            ["en"=>"Denmark","ru"=>"Дания"],
            ["en"=>"Djibouti","ru"=>"Джибути"],
            ["en"=>"Dominica","ru"=>"Доминика"],
            ["en"=>"Dominican Republic","ru"=>"Доминиканская Республика"],
            ["en"=>"East Timor","ru"=>"Восточный Тимор"],
            ["en"=>"Ecuador","ru"=>"Эквадор"],
            ["en"=>"Egypt","ru"=>"Египет"],
            ["en"=>"El Salvador","ru"=>"Сальвадор"],
            ["en"=>"Equatorial Guinea","ru"=>"Экваториальная Гвинея"],
            ["en"=>"Eritrea","ru"=>"Эритрея"],
            ["en"=>"Estonia","ru"=>"Эстония"],
            ["en"=>"Ethiopia","ru"=>"Эфиопия"],
            ["en"=>"Faeroe Islands","ru"=>""],
            ["en"=>"Falkland Islands","ru"=>"Фарерские острова"],
            ["en"=>"Fiji","ru"=>"Фиджи"],
            ["en"=>"Finland	","ru"=>"Финляндия"],
            ["en"=>"Former Yugoslav Republic of Macedonia","ru"=>"Македония"],
            ["en"=>"France","ru"=>"Франция"],
            ["en"=>"French Guiana","ru"=>"Гайана (Фр.)"],
            ["en"=>"French Polynesia","ru"=>"Полинезия (Фр.)"],
            ["en"=>"French Southern Territories","ru"=>"Французские южные территории"],
            ["en"=>"Gabon","ru"=>"Габон"],
            ["en"=>"Georgia","ru"=>"Грузия"],
            ["en"=>"Germany","ru"=>"Германия"],
            ["en"=>"Ghana","ru"=>"Гана"],
            ["en"=>"Gibraltar","ru"=>"Гибралтар"],
            ["en"=>"Greece","ru"=>"Греция"],
            ["en"=>"Greenland","ru"=>"Гренландия"],
            ["en"=>"Grenada","ru"=>"Гренада"],
            ["en"=>"Guadeloupe","ru"=>"Гваделупа (Фр.)"],
            ["en"=>"Guam","ru"=>"Гуам (США)"],
            ["en"=>"Guatemala","ru"=>"Гватемала"],
            ["en"=>"Guinea-Bissau","ru"=>"Гвинея-Бисау"],
            ["en"=>"Guyana","ru"=>"Гайана"],
            ["en"=>"Haiti","ru"=>"Гаити"],
            ["en"=>"Heard Island and McDonald Islands","ru"=>"Острова Хэрда и МакДональда"],
            ["en"=>"Honduras","ru"=>"Гондурас"],
            ["en"=>"Hong Kong","ru"=>"Гонг Конг"],
            ["en"=>"Hungary","ru"=>"Венгрия"],
            ["en"=>"Iceland","ru"=>"Исландия"],
            ["en"=>"India","ru"=>"Индия"],
            ["en"=>"Indonesia","ru"=>"Индонезия"],
            ["en"=>"Iran","ru"=>"Иран"],
            ["en"=>"Iraq","ru"=>"Ирак"],
            ["en"=>"Ireland","ru"=>"Ирландия"],
            ["en"=>"Israel","ru"=>"Израйль"],
            ["en"=>"Italy","ru"=>"Италия"],
            ["en"=>"Jamaica","ru"=>"Ямайка"],
            ["en"=>"Japan","ru"=>"Япония"],
            ["en"=>"Jordan","ru"=>"Иордания"],
            ["en"=>"Kazakhstan","ru"=>"Казахстан"],
            ["en"=>"Kenya","ru"=>"Кения"],
            ["en"=>"Kiribati","ru"=>"Кирибати"],
            ["en"=>"Kuwait","ru"=>"Кувейт"],
            ["en"=>"Kyrgyzstan","ru"=>"Киргизия"],
            ["en"=>"Laos","ru"=>"Лаос"],
            ["en"=>"Latvia","ru"=>"Латвия"],
            ["en"=>"Lebanon","ru"=>"Ливан"],
            ["en"=>"Lesotho","ru"=>"Лесото"],
            ["en"=>"Liberia","ru"=>"Либерия"],
            ["en"=>"Libya","ru"=>"Либия"],
            ["en"=>"Liechtenstein","ru"=>"Лихтейнштейн"],
            ["en"=>"Lithuania","ru"=>"Литва"],
            ["en"=>"Luxembourg","ru"=>"Люксембург"],
            ["en"=>"Macau","ru"=>"Макау"],
            ["en"=>"Madagascar","ru"=>"Мадагаскар"],
            ["en"=>"Malawi","ru"=>"Малави"],
            ["en"=>"Malaysia","ru"=>"Малайзия"],
            ["en"=>"Maldives","ru"=>"Мальдивы"],
            ["en"=>"Mali","ru"=>"Мали"],
            ["en"=>"Malta","ru"=>"Мальта"],
            ["en"=>"Marshall Islands","ru"=>"Маршальские острова"],
            ["en"=>"Martinique","ru"=>"Мартиника (Фр.)"],
            ["en"=>"Mauritania","ru"=>"Мавритания"],
            ["en"=>"Mauritius","ru"=>"Мавритий"],
            ["en"=>"Mayotte","ru"=>"Мейот"],
            ["en"=>"Mexico","ru"=>"Мексика"],
            ["en"=>"Micronesia","ru"=>"Микронезия"],
            ["en"=>"Moldova","ru"=>"Молдова"],
            ["en"=>"Monaco","ru"=>"Монако"],
            ["en"=>"Mongolia","ru"=>"Монголия"],
            ["en"=>"Montserrat","ru"=>"Монсеррат"],
            ["en"=>"Morocco","ru"=>"Морокко"],
            ["en"=>"Mozambique","ru"=>"Мозамбик"],
            ["en"=>"Myanmar","ru"=>"Бирма (Мьянма)"],
            ["en"=>"Namibia","ru"=>"Намибия"],
            ["en"=>"Nauru","ru"=>"Науру"],
            ["en"=>"Nepal","ru"=>"Непал"],
            ["en"=>"Netherlands","ru"=>"Нидерланды"],
            ["en"=>"Netherlands Antilles","ru"=>"Антиллы (Нидерланды)"],
            ["en"=>"New Caledonia","ru"=>"Новая Каледония (Фр.)"],
            ["en"=>"New Zealand","ru"=>"Новая Зеландия"],
            ["en"=>"Nicaragua","ru"=>"Никарагуаa"],
            ["en"=>"Niger","ru"=>"Нигер"],
            ["en"=>"Nigeria","ru"=>"Нигерия"],
            ["en"=>"Niue","ru"=>"Ниуэ"],
            ["en"=>"Norfolk Island","ru"=>"Норфолкские острова"],
            ["en"=>"North Korea","ru"=>"Северная Корея"],
            ["en"=>"Northern Marianas","ru"=>"Северные Марианские острова"],
            ["en"=>"Norway","ru"=>"Норвегия"],
            ["en"=>"Oman","ru"=>"Оман"],
            ["en"=>"Pakistan","ru"=>"Пакистан"],
            ["en"=>"Palau","ru"=>"Палау"],
            ["en"=>"Panama","ru"=>"Панама"],
            ["en"=>"Papua New Guinea","ru"=>"Папуа Новая Гвинея"],
            ["en"=>"Paraguay","ru"=>"Парагвай"],
            ["en"=>"Peru","ru"=>"Перу"],
            ["en"=>"Philippines","ru"=>"Филиппины"],
            ["en"=>"Pitcairn Islands","ru"=>"Питкерн"],
            ["en"=>"Poland","ru"=>"Польша"],
            ["en"=>"Portugal","ru"=>"Португалия"],
            ["en"=>"Puerto Rico","ru"=>"Пуэрто-Рико"],
            ["en"=>"Qatar","ru"=>"Катар"],
            ["en"=>"Réunion","ru"=>"Реюньон (Фр.)"],
            ["en"=>"Romania","ru"=>"Румыния"],
            ["en"=>"Russia","ru"=>"Россия"],
            ["en"=>"Rwanda","ru"=>"Руанда"],
            ["en"=>"São Tomé and Príncipe","ru"=>"Сан-Томе и Принсипи"],
            ["en"=>"Saint Helena","ru"=>"Остров Св.Елены"],
            ["en"=>"Saint Kitts and Nevis","ru"=>"Сент-Киттс Нэвис Ангуилла"],
            ["en"=>"Saint Lucia","ru"=>"Санта Лючия"],
            ["en"=>"Saint Pierre and Miquelon","ru"=>"Сен-Пьер и Микелон"],
            ["en"=>"Saint Vincent and the Grenadines","ru"=>"Сент-Висент и Гренадины"],
            ["en"=>"Samoa","ru"=>"Самоа"],
            ["en"=>"San Marino","ru"=>"Сан-Марино"],
            ["en"=>"Saudi Arabia","ru"=>"Саудовская Аравия"],
            ["en"=>"Senegal","ru"=>"Сенегал"],
            ["en"=>"Seychelles","ru"=>"Сейшеллы"],
            ["en"=>"Sierra Leone","ru"=>"Сьерра-Леоне"],
            ["en"=>"Singapore","ru"=>"Сингапур"],
            ["en"=>"Slovakia","ru"=>"Словакия"],
            ["en"=>"Slovenia","ru"=>"Словения"],
            ["en"=>"Solomon Islands","ru"=>"Соломоновы острова"],
            ["en"=>"Somalia","ru"=>"Сомали"],
            ["en"=>"South Africa","ru"=>"Южная Африка"],
            ["en"=>"South Georgia and the South Sandwich Islands","ru"=>"Южная Джорджия и Южные Сэндвичевы острова"],
            ["en"=>"South Korea","ru"=>"Южная Корея"],
            ["en"=>"Spain","ru"=>"Испания"],
            ["en"=>"Sri Lanka","ru"=>"Шри Ланка"],
            ["en"=>"Sudan","ru"=>"Судан"],
            ["en"=>"Suriname","ru"=>"Суринам"],
            ["en"=>"Svalbard and Jan Mayen","ru"=>"Сволборд и Ян Майен"],
            ["en"=>"Swaziland","ru"=>"Свазиленд"],
            ["en"=>"Sweden","ru"=>"Швеция"],
            ["en"=>"Switzerland","ru"=>"Швейцария"],
            ["en"=>"Syria","ru"=>"Сирия"],
            ["en"=>"Taiwan","ru"=>"Тайвань"],
            ["en"=>"Tajikistan","ru"=>"Таджикистан"],
            ["en"=>"Tanzania","ru"=>"Танзания"],
            ["en"=>"Thailand","ru"=>"Таиланд"],
            ["en"=>"The Bahamas","ru"=>"Багамы"],
            ["en"=>"The Gambia","ru"=>"Гамбия"],
            ["en"=>"Togo","ru"=>"Того"],
            ["en"=>"Tokelau","ru"=>"Токелау"],
            ["en"=>"Tonga","ru"=>"Тонга"],
            ["en"=>"Trinidad and Tobago","ru"=>"Тринидад и Тобаго"],
            ["en"=>"Tunisia","ru"=>"Тунис"],
            ["en"=>"Turkey","ru"=>"Турция"],
            ["en"=>"Turkmenistan","ru"=>"Туркменистан"],
            ["en"=>"Turks and Caicos Islands","ru"=>"Теркс и Кайкос"],
            ["en"=>"Tuvalu","ru"=>"Тувалу"],
            ["en"=>"US Virgin Islands","ru"=>"Вирджинские острова (США)"],
            ["en"=>"Uganda","ru"=>"Уганда"],
            ["en"=>"Ukraine","ru"=>"Украина"],
            ["en"=>"United Arab Emirates","ru"=>"Объединенные Арабские Эмираты"],
            ["en"=>"United Kingdom","ru"=>"Великобритания"],
            ["en"=>"United States","ru"=>"США"],
            ["en"=>"United States Minor Outlying Islands","ru"=>"	Внешние малые острова"],
            ["en"=>"Uruguay","ru"=>"Уругвай"],
            ["en"=>"Uzbekistan","ru"=>"Узбекистан"],
            ["en"=>"Vanuatu","ru"=>"Вануату"],
            ["en"=>"Vatican City","ru"=>"Ватикан"],
            ["en"=>"Venezuela","ru"=>"Венесуэла"],
            ["en"=>"Vietnam","ru"=>"Вьетнам"],
            ["en"=>"Wallis and Futuna","ru"=>"Уоллис и Футуна"],
            ["en"=>"Western Sahara","ru"=>"Западная Сахара"],
            ["en"=>"Yemen","ru"=>"Йемен"],
            ["en"=>"Yugoslavia","ru"=>"Югославия"],
            ["en"=>"Zambia","ru"=>"Замбия"],
            ["en"=>"Zimbabwe","ru"=>"Зимбабве"]
        ];
        foreach ($countries as $country){
            $new_country  = Country::create([]);
            $new_country->translateOrNew("en")->name=$country["en"];
            $new_country->translateOrNew("ru")->name=$country['ru'];
            $new_country->save();
        }
    }
}
